services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: final-project-dev-django-app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_DB: appdb
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: SuperSecret123!
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: final-project-dev-postgres
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: SuperSecret123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: