pipeline {
    agent {
        kubernetes {
            label 'kaniko'
        }
    }

    environment {
        AWS_REGION = 'us-west-2'
        ECR_REPO = '712242347745.dkr.ecr.us-west-2.amazonaws.com/final-project-dev-django-app'
        IMAGE_TAG = "${BUILD_NUMBER}"
        GIT_REPO = 'https://github.com/irina-hychka/goit-devops'
        BRANCH = 'final-project'
        HELM_VALUES_FILE = 'Project/charts/django-app/values.yaml'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: "${BRANCH}", url: "${GIT_REPO}"
            }
        }

        stage('Build & Push Image (Kaniko)') {
            steps {
                container('kaniko') {
                    sh """
                    /kaniko/executor \
                      --dockerfile=Project/Django/Dockerfile \
                      --context=${WORKSPACE}/Project/Django \
                      --destination=${ECR_REPO}:${IMAGE_TAG} \
                      --destination=${ECR_REPO}:latest \
                      --verbosity=info
                    """
                }
            }
        }

        stage('Update Helm values') {
            steps {
                container('git') {
                    withCredentials([usernamePassword(
                        credentialsId: 'github-creds',
                        usernameVariable: 'GIT_USERNAME',
                        passwordVariable: 'GIT_PASSWORD'
                    )]) {
                        sh """
                        git config --global user.email "jenkins@example.com"
                        git config --global user.name "jenkins"
                        git config --global --add safe.directory ${WORKSPACE}

                        sed -i 's/tag: .*/tag: "${IMAGE_TAG}"/' ${HELM_VALUES_FILE}

                        git add ${HELM_VALUES_FILE}
                        git commit -m "Update image tag to ${IMAGE_TAG}" || true
                        git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/irina-hychka/goit-devops ${BRANCH}
                        """
                    }
                }
            }
        }
    }
}