replicaCount: 2

image:
  repository: 712242347745.dkr.ecr.us-west-2.amazonaws.com/final-project-dev-django-app
  tag: "3"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaler:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

config:
  DJANGO_SETTINGS_MODULE: "core.settings"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  POSTGRES_HOST: "final-project-dev-postgres.xxxxxxxxxxxx.us-west-2.rds.amazonaws.com"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "appdb"
  POSTGRES_USER: "dbadmin"

secret:
  POSTGRES_PASSWORD: "SuperSecret123!"